package ein:plugin;

// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Mason Stallmo

world plugin {
    import ein:host/host;
    import process;

    export tool: interface {
        resource tool {
            constructor();
            name: func() -> string;
            schema: func() -> string;
            enable-chunk-sender: func() -> bool;
            call: func(id: string, args: string) -> result<string, string>;
        }
    }
}
